[2022-12-07T10:46:21.912+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.pull_data manual__2022-12-07T10:46:16.832820+00:00 [queued]>
[2022-12-07T10:46:21.927+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.pull_data manual__2022-12-07T10:46:16.832820+00:00 [queued]>
[2022-12-07T10:46:21.927+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T10:46:21.928+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-07T10:46:21.929+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T10:46:21.948+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): pull_data> on 2022-12-07 10:46:16.832820+00:00
[2022-12-07T10:46:21.953+0000] {standard_task_runner.py:55} INFO - Started process 1433 to run task
[2022-12-07T10:46:21.957+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag', 'pull_data', 'manual__2022-12-07T10:46:16.832820+00:00', '--job-id', '1703', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp2uahy6dv']
[2022-12-07T10:46:21.959+0000] {standard_task_runner.py:83} INFO - Job 1703: Subtask pull_data
[2022-12-07T10:46:22.042+0000] {task_command.py:376} INFO - Running <TaskInstance: dag.pull_data manual__2022-12-07T10:46:16.832820+00:00 [running]> on host ede3719a0239
[2022-12-07T10:46:22.129+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=lofitravel
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=pull_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-07T10:46:16.832820+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-07T10:46:16.832820+00:00
[2022-12-07T10:46:32.149+0000] {logging_mixin.py:137} INFO - could not translate host name "databasse" to address: Temporary failure in name resolution
[2022-12-07T10:46:32.150+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-07T10:46:32.166+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dag, task_id=pull_data, execution_date=20221207T104616, start_date=20221207T104621, end_date=20221207T104632
[2022-12-07T10:46:32.209+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-07T10:46:32.230+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
