[2022-12-07T19:44:16.673+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.insert_data manual__2022-12-07T19:43:58.035878+00:00 [queued]>
[2022-12-07T19:44:16.692+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.insert_data manual__2022-12-07T19:43:58.035878+00:00 [queued]>
[2022-12-07T19:44:16.692+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T19:44:16.693+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-07T19:44:16.694+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T19:44:16.736+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): insert_data> on 2022-12-07 19:43:58.035878+00:00
[2022-12-07T19:44:16.741+0000] {standard_task_runner.py:55} INFO - Started process 6761 to run task
[2022-12-07T19:44:16.747+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag', 'insert_data', 'manual__2022-12-07T19:43:58.035878+00:00', '--job-id', '1916', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp0yhv47u1']
[2022-12-07T19:44:16.748+0000] {standard_task_runner.py:83} INFO - Job 1916: Subtask insert_data
[2022-12-07T19:44:16.851+0000] {task_command.py:376} INFO - Running <TaskInstance: dag.insert_data manual__2022-12-07T19:43:58.035878+00:00 [running]> on host a9d6893ff63e
[2022-12-07T19:44:17.006+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=lofitravel
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-07T19:43:58.035878+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-07T19:43:58.035878+00:00
[2022-12-07T19:44:17.038+0000] {logging_mixin.py:137} INFO - var ['82adcbbbae7a13d16e0b68fa1f50c023', '***_user', '***_ps', '***_database']
[2022-12-07T19:44:17.050+0000] {logging_mixin.py:137} INFO - var ['82adcbbbae7a13d16e0b68fa1f50c023', '***_user', '***_ps', '***_database']
[2022-12-07T19:44:17.061+0000] {logging_mixin.py:137} INFO - var ['82adcbbbae7a13d16e0b68fa1f50c023', '***_user', '***_ps', '***_database']
[2022-12-07T19:44:17.078+0000] {logging_mixin.py:137} INFO - Postgresql connection created!
[2022-12-07T19:44:17.083+0000] {logging_mixin.py:137} INFO - duplicate key value violates unique constraint "pairs_pkey"
DETAIL:  Key (date, ticker_from, ticker_to)=(2022-12-07 00:00:00, USD, EUR) already exists.
[2022-12-07T19:44:17.085+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-07T19:44:17.109+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dag, task_id=insert_data, execution_date=20221207T194358, start_date=20221207T194416, end_date=20221207T194417
[2022-12-07T19:44:17.159+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-07T19:44:17.212+0000] {taskinstance.py:2623} INFO - 1 downstream tasks scheduled from follow-on schedule check
