[2022-12-06T20:38:00.829+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.task_0_0 manual__2022-12-06T20:37:50.022823+00:00 [queued]>
[2022-12-06T20:38:01.003+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.task_0_0 manual__2022-12-06T20:37:50.022823+00:00 [queued]>
[2022-12-06T20:38:01.007+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-06T20:38:01.010+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-06T20:38:01.015+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-06T20:38:01.289+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): task_0_0> on 2022-12-06 20:37:50.022823+00:00
[2022-12-06T20:38:01.436+0000] {standard_task_runner.py:55} INFO - Started process 2261 to run task
[2022-12-06T20:38:01.474+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag', 'task_0_0', 'manual__2022-12-06T20:37:50.022823+00:00', '--job-id', '1090', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp6hn9wnka']
[2022-12-06T20:38:01.499+0000] {standard_task_runner.py:83} INFO - Job 1090: Subtask task_0_0
[2022-12-06T20:38:02.480+0000] {task_command.py:376} INFO - Running <TaskInstance: dag.task_0_0 manual__2022-12-06T20:37:50.022823+00:00 [running]> on host 74768727baca
[2022-12-06T20:38:03.105+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=lofitravel
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=task_0_0
AIRFLOW_CTX_EXECUTION_DATE=2022-12-06T20:37:50.022823+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-06T20:37:50.022823+00:00
[2022-12-06T20:38:04.720+0000] {logging_mixin.py:137} INFO - курс одного USD к EUR: 0.95527698
[2022-12-06T20:38:04.743+0000] {xcom.py:600} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2022-12-06T20:38:04.790+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 18, in get_c
    ti.xcom_push(key='value', value=(date, ticker_from, ticker_to, value))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2385, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 212, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 597, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
[2022-12-06T20:38:04.936+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=dag, task_id=task_0_0, execution_date=20221206T203750, start_date=20221206T203800, end_date=20221206T203804
[2022-12-06T20:38:04.995+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1090 for task task_0_0 (Object of type datetime is not JSON serializable; 2261)
[2022-12-06T20:38:05.170+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-06T20:38:05.266+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
