[2022-12-07T14:49:05.837+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.insert_data manual__2022-12-07T14:48:56.860060+00:00 [queued]>
[2022-12-07T14:49:05.897+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.insert_data manual__2022-12-07T14:48:56.860060+00:00 [queued]>
[2022-12-07T14:49:05.899+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T14:49:05.900+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-07T14:49:05.903+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T14:49:05.977+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): insert_data> on 2022-12-07 14:48:56.860060+00:00
[2022-12-07T14:49:05.985+0000] {standard_task_runner.py:55} INFO - Started process 173 to run task
[2022-12-07T14:49:05.994+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag', 'insert_data', 'manual__2022-12-07T14:48:56.860060+00:00', '--job-id', '1797', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp2vzxe81c']
[2022-12-07T14:49:05.999+0000] {standard_task_runner.py:83} INFO - Job 1797: Subtask insert_data
[2022-12-07T14:49:06.182+0000] {task_command.py:376} INFO - Running <TaskInstance: dag.insert_data manual__2022-12-07T14:48:56.860060+00:00 [running]> on host 20d9dd97c6ff
[2022-12-07T14:49:06.397+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=lofitravel
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-07T14:48:56.860060+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-07T14:48:56.860060+00:00
[2022-12-07T14:49:06.461+0000] {logging_mixin.py:137} INFO - var ['82adcbbbae7a13d16e0b68fa1f50c023', '***_user', '***_ps', '***_database']
[2022-12-07T14:49:06.473+0000] {logging_mixin.py:137} INFO - var ['82adcbbbae7a13d16e0b68fa1f50c023', '***_user', '***_ps', '***_database']
[2022-12-07T14:49:06.486+0000] {logging_mixin.py:137} INFO - var ['82adcbbbae7a13d16e0b68fa1f50c023', '***_user', '***_ps', '***_database']
[2022-12-07T14:49:06.505+0000] {logging_mixin.py:137} INFO - Postgresql connection created!
[2022-12-07T14:49:06.507+0000] {logging_mixin.py:137} INFO - duplicate key value violates unique constraint "pairs_pkey"
DETAIL:  Key (date, ticker_from, ticker_to)=(2022-12-07 00:00:00, USD, EUR) already exists.
[2022-12-07T14:49:06.509+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-07T14:49:06.537+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dag, task_id=insert_data, execution_date=20221207T144856, start_date=20221207T144905, end_date=20221207T144906
[2022-12-07T14:49:06.612+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-07T14:49:06.673+0000] {taskinstance.py:2623} INFO - 1 downstream tasks scheduled from follow-on schedule check
